### ISSUE TITLE
Clearing out errors routine

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia-maintenance#122]
Hi @DhanshreeA 

This repo generates issues periodically - we should come up with a routine to clear out the errors/alarms. Should we allocate 1h/week to doing so? I think this could be very useful to maintain the hub.

Please let me know what you think.

**Comment by DhanshreeA** [comment]
Sounds good. I'll set up a schedule to do that.

**Comment by miquelduranfrigola** [comment]
Thanks @DhanshreeA 

The repo has now been fully transferred by @JuliaPoulson and @reneeperpignan , including a good README file and some minor improvements.

Let's keep building on this.
