### ISSUE TITLE
Add a check for extraneous files withis model repositories

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-maintenance#55]
Some models such as `eos2re5`, `eos526j`, `eos2b6f`, and `eos2r5a` and perhaps few more, that have an extraneous file called `place_a_dockerfile_in_current_eos_repo.py` at the root of these repositories.

There may also be other files such as `output.csv`, or `input.csv` at the root of these repositories. This files are usually generated during action workflows and if they're not removed during the workflow, they get committed to the model repository. We will need to add a check that flags repositories that do not adhere to model template file structure perhaps?

**Comment by miquelduranfrigola** [comment]
Hello @DhanshreeA we talked about this with @JuliaPoulson and @reneeperpignan last Thursday in our weekly meeting. Basically, they will check that no files others than the specified in the `eos-template` are present in the root of the repository. This should be sufficient!

**Comment by miquelduranfrigola** [comment]
This has been nicely solved. Closing the issue.
