### ISSUE TITLE
T4SG Handover

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia-maintenance#97]
Hi @JuliaPoulson and @reneeperpignan !

Thanks again for an outstanding work on this repository. Today I have shown it to @DhanshreeA and she was equally impressed.

In this issue, I just want to highlight a few items to wrap up, based on our discussion.

- [ ] Documentation can be centralized in the `README` file. It would be good it we could get some guidance on how to extend the current checks (for example, to check a new field in the metadata file). It is likely that we will add more tests in the future!
- [ ] Send the slides from yesterday's presentation. Those were very useful.
- [ ] I have noticed that the YAML file is called `valid_url.yml`. Do you think we could change it to something more general, such as `inspect_model.yml`?
- [ ] Would it make sense to store log data as an artifact of the job? It would be so interesting to keep metadata of these runs somewhere, for example in S3, especially because you are doing performance test that could be very informative for us. I realize this may not be easy, so please feel free to overlook this point.

Finally, as agreed, there is no need to automatically fix issues. So we can leave this item out.

Let me know what you think. Thanks a lot!

**Comment by DhanshreeA** [comment]
I am closing this issue as stale.
